

-- hint shuffle
CREATE TABLE TEST_DATASET("PID" integer, "COLUMNNO" integer, "ATT" char(100),"DECISION" char(100), "ISNUMERIC" integer, "WEIGHT" integer)
CREATE TABLE TRAIN_DATASET("PID" integer, "COLUMNNO" integer, "ATT" char(100),"DECISION" char(100), "ISNUMERIC" integer, "WEIGHT" integer)

with  NBC(COL, ATT, DECISION, PROBABILITY) as
(SELECT COLUMNNO, ATT, DECISION, SUM(WEIGHT)
  FROM TRAIN_DATASET
  WHERE ISNUMERIC=0
   GROUP BY (COLUMNNO, DECISION, ATT)),

LABELS(DECISION) AS
(SELECT DISTINCT DECISION FROM TEST_DATASET),

COMB (COL, ATT, DECISION, PROBABILITY ) as
(SELECT DISTINCT COLUMNNO, ATT, LABELS.DECISION, 1
FROM TEST_DATASET, LABELS WHERE ISNUMERIC=0),

create view NBC(COL, ATT, DECISION, PROBABILITY) as
(SELECT * FROM COMB WHERE (COL,ATT,DECISION)
NOT IN (SELECT COL,ATT,DECISION FROM NBC))

with NBC_CLASS(DECISION, PROBABILITY) as
  (SELECT DECISION, SUM(WEIGHT) FROM TRAIN_DATASET WHERE COLUMNNO = 1 GROUP BY DECISION),

NBC_CLASSK(DECISION, PROBABILITY) as
  (SELECT DECISION, PROBABILITY+1 FROM NBC_CLASS),


NBC_WT(COL, ATT, DECISION, PROBABILITY) as
(SELECT COL,ATT,N1.DECISION, CAST(N1.PROBABILITY AS DECIMAL(6,0)) / CAST(N2.PROBABILITY AS DECIMAL(6,0))
FROM NBC AS N1,NBC_CLASSK AS N2
WHERE N1.DECISION = N2.DECISION)

create view STATS(COLUMNNO, MEAN, VARIANCE , DECISION)
(SELECT COLUMNNO, AVG(ATT), VARIANCE(ATT), DECISION FROM TRAIN_DATASET WHERE ISNUMERIC=1 GROUP BY COLUMNNO, DECISION)

WITH PROBABILITY(ROW, PREDICTED, PROB) AS
		((SELECT TEST_DATASET.PID, NBC_WT.DECISION, NBC_WT.PROBABILITY
			FROM TEST_DATASET, NBC_WT
			WHERE TEST_DATASET.COLUMNNO = NBC_WT.COL
			AND TEST_DATASET.ATT = NBC_WT.ATT)
			UNION ALL
			(SELECT T.PID, S.DECISION, ((1/(SQRT(2*3.14*S.VARIANCE)))*(EXP(-POWER((T.ATT-S.MEAN),2)/(2*S.VARIANCE))))
			FROM TEST_DATASET T, STATS S
			WHERE T.COLUMNNO = S.COLUMNNO)
			),
PROBABILITYSUM(ROW, PREDICTED, PROB) AS
		(SELECT ROW, PREDICTED, SUM(LOG(PROB)) FROM PROBABILITY GROUP BY ROW, PREDICTED),
		WEIGHTPROB(ROW, PREDICTED, PROB) AS
		(SELECT PROBABILITYSUM.ROW, PROBABILITYSUM.PREDICTED, PROBABILITYSUM.PROB + LOG(NBC_CLASS.PROBABILITY)
		FROM PROBABILITYSUM, NBC_CLASS
		WHERE PROBABILITYSUM.PREDICTED = NBC_CLASS.DECISION),
		MAXPROB(ROW, PROBABILITY) AS
		(SELECT ROW, MAX(PROB) FROM WEIGHTPROB GROUP BY ROW)

create view TEST_RESULTS(COLUMN, ACTUAL, PREDICTED) as
	(SELECT TD.PID, TD.DECISION, WP.PREDICTED
	FROM TEST_DATASET as TD, MAXPROB as MP, WEIGHTPROB AS WP
	WHERE TD.PID = MP.ROW
	AND TD.PID = WP.ROW
	AND MP.PROBABILITY = WP.PROB
	AND TD.COLUMNNO = 1)

WITH SUCCESS(NUM) AS
			(SELECT COUNT(PREDICTED) FROM TEST_RESULTS WHERE PREDICTED = ACTUAL),
TOTAL(NUM) AS
			(SELECT COUNT(PREDICTED) FROM TEST_RESULTS)


create view COMBINED_RESULTS(ACCURACY) as
  (SELECT CAST(SUCCESS.num AS DECIMAL(10,0))/CAST(TOTAL.num AS DECIMAL(10,0))
  FROM SUCCESS, TOTAL)
